--- 
- name: Homework
  hosts: all
  tasks:
    - name: Build database image
      docker_image:
        name: database:latest
        tag: database
        source: build
        force_source: yes
        build: 
          path: database
          pull: yes
          

    - name: Starting Docker Container database
      docker_container:
        name: database
        image: database:latest
        recreate: yes
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: auradb
          POSTGRES_USER: aura
          POSTGRES_PASSWORD: aurapassword


    - name: Create private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: ./web/certificate.key

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: ./web/certificate.pem
        privatekey_path: ./web/certificate.key
        provider: selfsigned

    - name: Build web image
      docker_image:
        name: web:latest
        tag: web
        source: build
        force_source: yes
        build:
          path: web
          pull: yes

    - name: Starting Docker Container web
      docker_container:
        name: web
        image: web:latest
        recreate: yes
        state: started
        ports: 
          - "9443:443"
          - "80:80"

    - name: Create network and add containers
      docker_network:
        name: network_one
        connected:
          - database
          - web
