#!/bin/sh
service nginx start
while true 
do
   psql -H --command="SELECT * FROM users;" postgresql://aura:aurapassword@database:5432/auradb > index.body
   cat index.ini index.body index.end > index.html
   sleep 1
done

